name: amptools
channels:
- conda-forge
- defaults
dependencies:
- ipython
- jupyter
- lxml
- matplotlib
- numpy>=1.14
- obspy
- pandas
- pytest
- pytest-cov
- python=3.6
- pyyaml
- xlrd
- xlwt
- openpyxl
- obspy
- xlsxwriter
- cython
- gcc
